### ISSUE TITLE
Error when executing: last_published = datetime.strptime(cv["last_published"], '%Y-%m-%d  %X %Z')

### ISSUE THREAD

**Issue by MikeDawg** [ture-karlsson/katello-publish-cvs#2]
Hi Everyone, I'm running into this issue when executing katello-publish-cvs.py. It seems to be erroring at on the last_published line of the script, and my python kung-fu isn't good enough to overcome this error. Any help would be appreciated.

------

./katello-publish-cvs
Organization "Censored has ID: 1
Lifecycle environments: {u'QA': 5, u'Development': 2, u'Production': 7, u'UAT': 6, u'Library': 1}
Satellite6 doesn't need to be published
RHEV Base doesn't need to be published
Red Hat RHEL7 Base doesn't need to be published
Red Hat RHEL6 Base doesn't need to be published
Red Hat RHEL5 Base doesn't need to be published
Puppet Enterprise EL7 doesn't need to be published
Puppet Enterprise EL6 doesn't need to be published
Puppet Enterprise EL5 doesn't need to be published
Puppet Enterprise doesn't need to be published
OSE Registry doesn't need to be published
Traceback (most recent call last):
  File "./katello-publish-cvs", line 170, in <module>
    main()
  File "./katello-publish-cvs", line 115, in main
    last_published = datetime.strptime(cv["last_published"], '%Y-%m-%d  %X %Z')
TypeError: strptime() argument 1 must be string, not None

**Comment by MikeDawg** [comment]
I'm *guessing* that this problem might be if last_published is None, because it never has been updated? _OR_ is it some unused CV?

Again, don't have the python knowledge/skills, but I have to imagine it would be fixing/allowing last_published to be "None" in the case that the CV was never promoted, before?

**Comment by ture-karlsson** [comment]
Hi MikeDawg!

It indeed looks like there is one or more CVs in your Satellite that have never been published before running the script. Can you confirm that? If you publish them manually before running the script, I suspect it runs without issues.

Either way, I should fix the script so that it handles the case where last_published is "None". I don't have time right now, but I will put it on my todo list.

Thanks for reporting!
