### ISSUE TITLE
KeyError: Library

### ISSUE THREAD

**Issue by MikeDawg** [ture-karlsson/katello-publish-cvs#3]
```
root@<REDACTED>:/root> ./katello-publish-cvs.py
Organization "<REDACTED>s has ID: 1
Lifecycle environments: {u'SI6.1': 73, u'SI5.11': 53, u'SI6.3': 77, u'SI6.2': 75, u'SI7': 33, u'SI7.1': 85, u'SI7.2': 83, u'SI7.3': 11, u'SI6.9': 89, u'SI6.8': 91, u'SI6.6': 95, u'SI6': 31, u'SI6.7': 93, u'SI6.5': 81, u'SI5.10': 49, u'SI7.0': 87, u'SI5.9': 69, u'SI5': 29, u'SI5.8': 67, u'SI6.4': 79}
Satellite Tools doesn't need to be published
RHSCL_7 doesn't need to be published
RHSCL_6 doesn't need to be published
RHEL7.3 doesn't need to be published
RHEL7.2 doesn't need to be published
RHEL7.1 doesn't need to be published
RHEL7.0 doesn't need to be published
RHEL 7 doesn't need to be published
RHEL7 doesn't need to be published
RHEL6.9 doesn't need to be published
RHEL6.8 doesn't need to be published
RHEL6.7 doesn't need to be published
RHEL6.6 doesn't need to be published
RHEL6.5 doesn't need to be published
RHEL6.4 doesn't need to be published
RHEL6.3 doesn't need to be published
RHEL6.2 doesn't need to be published
RHEL6.1 doesn't need to be published
RHEL 6 doesn't need to be published
RHEL6 doesn't need to be published
Waiting for publish tasks to finish...
Finished waiting after 0 seconds
Traceback (most recent call last):
  File "./katello-publish-cvs.py", line 172, in <module>
    main()
  File "./katello-publish-cvs.py", line 151, in main
    if ENVIRONMENTS["Library"] in version["environment_ids"]:
KeyError: 'Library'
```

Again, I'm unsure what I can do to provide more information, or more assistance in troubleshooting this error.

**Comment by ture-karlsson** [comment]
I think this is the same reason as the last issue, namely that there is one or more CVs that have never been published. Can you verify that all CVs are published at least once, and if not publish them once manually? Then try to run the script again.

I will test this and make sure that the script publish unpublished CVs as well for robustness.

**Comment by MikeDawg** [comment]
I can confirm, as I actually have access to the Satellite Server this time. I can confirm that all CVs and CCVs are published, where I confirmed that there was an unpublished CV/CCV in the first "issue" I pinged you on.

**Comment by MikeDawg** [comment]
So, in "downgrading" to an older version, I am experiencing the same/similar error.  I 'downgraded' to the release with the tag dd01df0; and I got the following error, similar, although there are some line differences.

```
RHEL6.4 doesn't need to be published
RHEL6.3 doesn't need to be published
RHEL6.2 doesn't need to be published
RHEL6.1 doesn't need to be published
RHEL 6 doesn't need to be published
RHEL6 doesn't need to be published
Waiting for publish tasks to finish...
Finished waiting after 0 seconds
Traceback (most recent call last):
  File "./katello-publish-cvs.py", line 169, in <module>
    main()
  File "./katello-publish-cvs.py", line 148, in main
    if ENVIRONMENTS["Library"] in version["environment_ids"]:
KeyError: 'Library'

```

**Comment by ture-karlsson** [comment]
It looks like the script is not able to read the lifecycle environments correct, since it can't find "Library" in ENVIRONMENTS. There is a line printing the ENVIRONMENTS dictionary in the beginning of the main method. For me, the first two lines the output are the following:

Organization "Default Organization" has ID: 1
Lifecycle environments: {u'TEST': 9, u'PROD': 10, u'DEV': 8, u'Library': 7}

As you see, it contains the lifecycle path Library -> DEV -> TEST -> PROD. What does that line say on your Satellite?

**Comment by MikeDawg** [comment]
So, is the API affected by the same limitations that hammer is, in the fact, that hammer can only display 20 lifecycle-environments; or is this a non-issue for the API?

What I might suggest using/testing is set up a Satellite instance where there are more than 20 lifecycle-environments and see if this can still parse the tree.

**Comment by ture-karlsson** [comment]
I saw that you already had pasted the lifecycle environments output, hence I removed my comment yesterday.

You are correct that the API does only return 20 lifecycle environments by default. It didn't cross my mind to test with more than that. I've added a fix with "per_page=999" in last commit. I guess you don't have more lifecycle environments than that in your organization? :)

Please test and report back your findings.

**Comment by ture-karlsson** [comment]
I can confirm that it works on my Satellite when I add 20+ lifecycle environments.

**Comment by ture-karlsson** [comment]
@MikeDawg did the last fix solve your problem? If so, we can close this issue.

**Comment by MikeDawg** [comment]
Let me test one last time today, on a new 6.2.10 install, I'll update, hopefully by end of day, after upgrade completes.

**Comment by MikeDawg** [comment]
Confirmed that it now works. Thanks for the updates!
